spring:
  profiles:
    default: dev
---
spring:
  application:
    name: profile
  config:
    import: configserver:http://localhost:8079
    activate:
      on-profile: dev
---
spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: configserver:${CONFIG_SERVER_URL}
    activate:
      on-profile: prod
