spring:
  application:
    name: profile
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8079
---
spring:
  application:
    name: ${APPLICATION_NAME}
  config:
    import: configserver:${CONFIG_SERVER_URL}
    activate:
      on-profile: prod
