version: "3.9"
services:
  profile_db:
    image: mysql:latest
    container_name: profile_db
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_TCP_PORT=3310
    ports:
      - "3310:3310"
    volumes:
      - profile-db-volume:/var/lib/mysql
    networks:
      microservice-network:
        aliases:
            - "profiledb"
  config_server:
    image: config-server
    ports:
      - "8079:8079"
    networks:
      microservice-network:
       aliases:
          - "configserver"
  profile:
    image: profile
    ports:
      - "8081:8081"
    environment:
      - APPLICATION_NAME=profile
      - CONFIG_SERVER_URL=http://configserver:8079
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      config_server:
        condition: service_started
      profile_db:
        condition: service_started
    networks:
      - microservice-network
volumes:
  profile-db-volume:
networks:
  microservice-network:

